spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/practicebank
    password: patrick
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: trace

application:
  security:
    jwt:
      secret-key: 6jZy59I3gNLH1Pj45sJT9/E0SSQUA1yNcAV1yZaXiwE
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 1 week

  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'false'
    hibernate:
      ddl-auto: create-drop
